ktor:
  application:
    modules:
      - com.sayesamanappointmentbookingsystem.ApplicationKt.module
  deployment:
    port: 8080
  storage :
    driverClassName : "com.mysql.cj.jdbc.Driver"
    jdbcURL : "jdbc:mysql://127.0.0.1:3306/barber?user=aria=y7Ay6n1vfnfVjBgV"